apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: Petstore
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  lifecycle: experimental
  owner: viaops-internal/viaops
  implementsApis:
    - petstore
