site_name: 'petstore'
site_description: 'Main documentation for Backstage features and platform APIs'

nav:
  - Home: index.md

metadata:
  annotations:
    backstage.io/techdocs-ref: dir:./

plugins:
  - techdocs-core

