apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
